# frozen_string_literal: true

module Agentf
  module AgentRoles
    ORCHESTRATOR = "ORCHESTRATOR"
    PLANNER = "PLANNER"
    ENGINEER = "ENGINEER"
    REVIEWER = "REVIEWER"
    KNOWLEDGE_MANAGER = "KNOWLEDGE_MANAGER"
    RESEARCHER = "RESEARCHER"
    QA_TESTER = "QA_TESTER"
    INCIDENT_RESPONDER = "INCIDENT_RESPONDER"
    UI_ENGINEER = "UI_ENGINEER"
    SECURITY_REVIEWER = "SECURITY_REVIEWER"

    ALL = [
      ORCHESTRATOR,
      PLANNER,
      ENGINEER,
      REVIEWER,
      KNOWLEDGE_MANAGER,
      RESEARCHER,
      QA_TESTER,
      INCIDENT_RESPONDER,
      UI_ENGINEER,
      SECURITY_REVIEWER
    ].freeze
  end
end
